# Python basics

## Introduction to optimization and operations research.

Michel Bierlaire


In [1]:

import numpy as np
from IPython.core.display_functions import display


# Introduction to Python features

Python is a widely used high-level programming language known for its readability, simplicity, and versatility.
It is used across many domains, including data analysis, artificial intelligence, web development, and scientific
computing. In this course, Python serves as a practical tool to formulate and solve optimization problems. While
Python is a programming language, it has been designed to be accessible even to those without a background in
computer science. You do not need to be a programmer to follow the course or complete the exercises.

The use of AI agents such as ChatGPT can be helpful — for example, to assist with writing or debugging small
pieces of code — but it is absolutely not required. The course is structured to guide you through the relevant
features of Python step by step, and no prior programming experience is assumed. Some basic elements of Python are
introduced below. If you are curious to learn more, you will also find a wealth of tutorials and documentation
freely available online.

This notebook provides introductory examples of Python to help you understand basic programming concepts.
It is intended as a reference and learning resource — you are not expected to modify this file.
Use it to explore how Python works and to support your understanding of the course material.

Python allows you to define variables of various types depending on the kind of data you need to store.
The most common types are:
- Integer: whole numbers (e.g., 1, 2, 100)
- Float: numbers with decimals (e.g., 3.14, 2.0)
- String: sequences of characters used for text (e.g., 'hello')
- Boolean: logical values representing True or False
Below is an example showing how to define and display each of these variable types.

In [2]:
print('\n### Variables and Data Types ###')
integer_var = 10  # Integer
float_var = 3.14  # Floating point number
string_var = 'Welcome to the optimization course'  # String
boolean_var = True  # Boolean
print('Integer:', integer_var)
print('Float:', float_var)
print('String:', string_var)
print('Boolean:', boolean_var)



### Variables and Data Types ###
Integer: 10
Float: 3.14
String: Welcome to the optimization course
Boolean: True


In Python, variables can hold values of any type, and the type can change during program execution.
However, it's possible (and good practice) to add *type annotations* to indicate what kind of data is expected.
For example, writing `integer_var: int = 10` tells readers and tools that `integer_var` is intended to hold an integer.
These annotations improve code readability and make it easier to catch type-related mistakes using tools like linters or IDEs.
Note: type annotations are not enforced at runtime — they are mainly for documentation and development support.

In [3]:
integer_var: int = 10
float_var: float = 3.14
string_var: str = 'Welcome to the optimization course'
boolean_var: bool = True



Python supports several types of data structures that allow you to organize and store data in useful ways.
One commonly used structure is the `list`, which is a collection of items ordered by position (i.e., indexed).
Lists are useful when you want to keep track of multiple related values, like a sequence of names or numbers.
In Python, lists are *mutable*, which means you can change them after they are created:
you can add new elements, remove elements, or change the values of existing elements.

In [4]:
print('\n### Lists ###')
mathematicians = ['Euler', 'Newton', 'Bernoulli']
print('Mathematicians list :', mathematicians)
print(
    'First mathematician:', mathematicians[0]
)  # Access first element. Numbering starts at 0.
print('Last mathematician:', mathematicians[-1])  # Access last element.
mathematicians.append('Dantzig')  # Add an element
print('Updated list:', mathematicians)



### Lists ###
Mathematicians list : ['Euler', 'Newton', 'Bernoulli']
First mathematician: Euler
Last mathematician: Bernoulli
Updated list: ['Euler', 'Newton', 'Bernoulli', 'Dantzig']


Python provides a feature called "slicing" to extract portions of a list.
The slicing syntax is: list[start:stop]
This creates a new list that includes elements starting from index 'start' and up to, but not including, index 'stop'.
For example, list[1:4] will give you the elements at index 1, 2, and 3.
If you omit 'start', it begins from the start of the list; if you omit 'stop', it goes until the end.
Python also supports negative indices:
- Index -1 refers to the last element
- Index -2 refers to the second-to-last, and so on.
This is useful for working with the tail of a list or extracting ranges relative to the end.

In [5]:
sublist = mathematicians[1:-1]
print(f'Extracted range: {sublist}')


Extracted range: ['Newton', 'Bernoulli']


Tuples are ordered collections of items, similar to lists.
However, unlike lists, tuples are *immutable*, which means that their contents
cannot be changed once the tuple is created. You cannot add, remove, or modify
any element in a tuple.

Tuples are useful when you want to store a fixed set of values that should
not be altered by the program — for example, a coordinate pair (x, y), where
the values represent a specific point in space and must remain constant.
This immutability helps prevent unintended changes to the data.

In [44]:
print('\n### Tuples ###')
coordinates = (10, 20)
print('Coordinates:', coordinates)



### Tuples ###
Coordinates: (10, 20)


Dictionaries are a built-in data structure in Python that store information as key-value pairs.
Each key must be unique, and is used to access the corresponding value.
Dictionaries are enclosed in curly braces {}, with keys and values separated by colons.
For example: {'name': 'Alice', 'age': 20} is a dictionary with two entries.
You can access values by using their keys, like `dictionary['name']` returns 'Alice'.
Dictionaries are mutable: you can add, modify, or delete entries after the dictionary is created.
This makes them very useful for representing structured data, such as properties of an object
(e.g., a student with a name, age, and grade).

In [7]:
print('\n### Dictionaries ###')
student = {'name': 'Alice', 'age': 20, 'grade': 5.75}
print('Student Dictionary:', student)
print('Student name:', student['name'])



### Dictionaries ###
Student Dictionary: {'name': 'Alice', 'age': 20, 'grade': 5.75}
Student name: Alice


Conditional statements allow a Python program to perform different actions depending on whether certain conditions are true or false.
The most common conditional structure starts with `if`, which checks whether a condition is true.
If the condition is true, the indented block of code that follows will be executed.
If the `if` condition is false, you can test another condition using `elif` (short for "else if").
If none of the `if` or `elif` conditions are met, an `else` block can be used to execute a default action.
This allows the program to make decisions and respond appropriately to different input values or situations.
Indentation (spacing at the beginning of a line) is very important in Python: it defines which code belongs to which block.

In [8]:
print('\n### Conditionals ###')
num = 7
if num > 5:
    print('The number is greater than 5')
elif num == 5:
    print('The number is 5')
else:
    print('The number is less than 5')



### Conditionals ###
The number is greater than 5


Loops in Python are a fundamental programming tool that let you repeat a block of code multiple times without writing it out manually.
There are two main types of loops: `for` loops and `while` loops.

A `for` loop is used when you want to iterate over a sequence of values — such as a list, a string, or a range of numbers.
It automatically assigns each item in the sequence to a variable, and executes the loop body once for each item.

In the example below, we use `range(5)`, which generates a sequence of numbers from 0 to 4 (inclusive of 0, exclusive of 5),
and `i` will take on each of these values in turn. The `print` statement inside the loop will be executed five times,
once for each value of `i`.

In [9]:
print('\n### Loops ###')
print('For loop example:')
for i in range(5):  # Loop from 0 to 4
    print('Iteration:', i)



### Loops ###
For loop example:
Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4



A `while` loop in Python repeatedly executes a block of code as long as a specified condition remains true.
The loop checks the condition before each iteration, and if it is still true, it runs the code block again.
This is useful when the number of iterations is not known in advance, and you want to keep looping until some event or condition occurs.
In the example below, the loop runs as long as `x > 0`. Inside the loop, `x` is decremented by 1 at each step.
This ensures that eventually the condition `x > 0` becomes false, and the loop stops.
Be cautious: if the condition never becomes false (for example, if `x` is never decreased), the loop will run forever — this is called an infinite loop.

In [10]:
print('While loop example:')
x = 3
while x > 0:
    print('Countdown:', x)
    x -= 1



While loop example:
Countdown: 3
Countdown: 2
Countdown: 1



Functions in Python allow you to define a reusable block of code that performs a specific task.
They are useful for organizing your code, avoiding repetition, and improving clarity.
A function can take one or more *parameters* as input, and can optionally return a result.

In the example below, the function is named `greet`, and it takes a single input `name` which is expected to be a string.
The function returns a string formatted with a greeting message.

The type hints (`name: str` and `-> str`) are optional: they indicate that the input should be a string,
and the function will return a string. These hints are helpful for people reading the code and for tools
that check your code for potential issues.

In [11]:
def greet(name: str) -> str:
    '''Returns a greeting message for the given name.'''
    return f'Hello, {name}!'


print(greet('Alice'))


Hello, Alice!



Writing to a file:
In Python, you can write text to a file using the built-in `open()` function.
The 'with' statement ensures the file is automatically closed after the writing is done,
which is a best practice to avoid leaving files open accidentally.
Opening a file in write mode ('w') will:
- create the file if it does not exist,
- or overwrite its contents if it already exists.
In this example, we open the file named 'example.txt' and write three lines into it.

In [12]:
filename = 'example.txt'

with open(filename, 'w') as file:
    file.write('This is a simple text file.\n')
    file.write('Python makes file handling easy!\n')
    print('Another line written using print()', file=file)


Reading from a file:
To read the contents of a file, we open it using the built-in `open()` function with mode 'r', which stands for "read".
The 'with' statement is used to manage the file context: it ensures that the file is automatically closed after reading,
even if an error occurs. This is good practice and prevents file-handling issues.
The `read()` method reads the entire contents of the file as a single string.
If the file contains multiple lines, they will be separated by newline characters (`\n`) in the string.

In [13]:
with open(filename, 'r') as file:
    content = file.read()
    print('File Content:\n', content)


File Content:
 This is a simple text file.
Python makes file handling easy!
Another line written using print()




Exception Handling in Python:

When you write a program, it's common to encounter situations where errors may occur — for example,
trying to divide a number by zero, opening a file that doesn't exist, or converting text to a number.
Python provides a way to handle such situations gracefully using *exception handling*.

A `try` block contains code that might raise an error during execution.
If an error (called an "exception") occurs, Python stops executing the `try` block and looks for an `except` block
that matches the type of error. If a matching `except` block is found, its code runs instead of crashing the program.

An optional `finally` block contains code that always runs, no matter what — whether an exception occurred or not.
This is useful for cleanup tasks like closing a file or releasing a resource.

In the example below, we attempt to divide by zero, which raises a `ZeroDivisionError`.
Instead of crashing, the program catches the exception and prints a helpful message.

In [14]:
try:
    result = 10 / 0  # This will raise a ZeroDivisionError
except ZeroDivisionError:
    print('Cannot divide by zero!')
finally:
    print('Execution completed.')



Cannot divide by zero!
Execution completed.


# f-Strings in Python

f-strings, short for "formatted string literals," are a convenient and readable way to include variables or expressions directly within strings.
You simply prefix the string with the letter `f`, and then place expressions inside curly braces `{}`.
Python will evaluate those expressions and insert their values into the resulting string.

## Basic usage

In [15]:
name: str = 'Ada'
age: int = 36
print(f'{name} is {age} years old.')


Ada is 36 years old.


## Arithmetic expressions inside f-strings
f-strings (formatted string literals) let you include not just variables,
but also expressions directly inside the curly braces {}.
For example, you can perform arithmetic like addition or multiplication
right inside the string, which makes the code more concise and readable.
The expression will be evaluated and its result will be inserted into the string output.

In [16]:
a: int = 3
b: int = 4
print(f'The sum of {a} and {b} is {a + b}.')


The sum of 3 and 4 is 7.


## Floating-point formatting
When printing floating-point numbers (like decimals), it’s often useful to control how many digits appear after the decimal point.
This can make the output cleaner and more readable, especially when displaying results like prices, measurements, or percentages.
In an f-string, you can specify the number of decimal places using the format `{value:.nf}` where `n` is the number of digits.
For example, `{pi:.2f}` rounds the value of pi to 2 decimal places (e.g., 3.14).

In [17]:
pi: float = 3.1415926535
print(
    f'The value of pi rounded to 2 decimals is {pi:.2f}.'
)  # .2f formats float with 2 decimals


The value of pi rounded to 2 decimals is 3.14.


## Padding and alignment
When printing multiple values in a table-like format, it's helpful to align the text within fixed-width fields.
This makes the output easier to read and compare.
You can specify alignment using formatting codes inside an f-string:
- `<` left-aligns the text in the field
- `^` centers the text
- `>` right-aligns the text
The number after the symbol indicates the width of the field (e.g., 10 characters wide).
In the example below, each word is aligned inside a 10-character wide field,
and the output is visually enclosed in vertical bars to highlight the alignment.

In [46]:
print(f'|{"left":<10}|{"center":^10}|{"right":>10}|')


|left      |  center  |     right|


## Number formatting
When working with large numbers, it's helpful to make them easier to read by adding separators.
Python's f-string formatting supports this with the `:,` format specifier, which adds commas (or locale-specific separators)
to separate groups of digits in large numbers. This is especially useful for printing values like population sizes,
financial figures, or any other quantity with many digits.

In [48]:
large_number: int = 1_000_000
print(f'Population [without formatting]: {large_number}')
print(
    f'Population [with formatting]: {large_number:,}'
)  # adds commas to format as 1,000,000 instead of 1000000



Population [without formatting]: 1000000
Population [with formatting]: 1,000,000


## Using expressions and function calls
f-strings not only allow you to include variables directly in strings,
but you can also include expressions or function calls.
For example, if you define a function that computes the square of a number,
you can call that function inside an f-string to display the result dynamically.
This is very useful for creating formatted messages that reflect the outcome of calculations.

In [49]:
def square(x: int) -> int:
    return x * x


n: int = 5
print(f'The square of {n} is {square(n)}.')



The square of 5 is 25.


## Using dictionaries with f-strings
You can use dictionary values directly inside f-strings by referring to them using their keys.
This is especially helpful when formatting output from structured data stored in dictionaries.
Make sure to use double quotes for the key (e.g., info["mass"]) inside the curly braces.
In the example below, we extract and format the values for mass and velocity from a dictionary.

In [21]:
info: dict[str, float] = {'mass': 70.5, 'velocity': 3.2}
print(f'Mass: {info["mass"]} kg, Velocity: {info["velocity"]} m/s')


Mass: 70.5 kg, Velocity: 3.2 m/s


# NumPy Tutorial: Vectors, Matrices, and Operations

NumPy is a powerful and widely used library in Python for performing numerical computations efficiently.
It is especially useful for working with large arrays and matrices of numerical data, and includes many functions
for linear algebra, statistics, and more. NumPy arrays behave differently from regular Python lists:
they are more efficient in terms of memory and speed, and allow element-wise operations and broadcasting,
which makes many mathematical operations easier to write and understand.

In this section, we will introduce basic concepts of NumPy, including how to create vectors and matrices,
how to perform simple operations with them, and how to use some of the linear algebra tools provided by the library.
If you are new to programming or numerical computing, don’t worry — we’ll proceed step by step with examples.

## Vectors

In Python, a vector is often represented using a 1-dimensional NumPy array.
NumPy is a powerful library for numerical computations that makes it easy to handle vectors and matrices.
To create a vector, we use the function np.array() and pass in a list of numbers.
Each element in the list becomes a component of the vector.
Once the vector is created, we can print it, perform mathematical operations, or access individual elements.

In [22]:
vector: np.ndarray = np.array([1, 2, 3])
print('Vector:', vector)


Vector: [1 2 3]


You can access individual elements of a NumPy array using indices, just like with Python lists.
Indexing starts at 0, so the first element has index 0, the second has index 1, and so on.
For example, vector[1] accesses the second element of the array (which is 2 in this case).

In [23]:
print('Second element:', vector[1])


Second element: 2


## Matrices

A matrix is a two-dimensional (2D) array, which means it is made up of rows and columns.
In NumPy, you can represent a matrix as an array of arrays — where each inner array represents a row.
It is important that all rows have the same number of elements; otherwise, NumPy will not treat it as a proper 2D array.
Matrices are useful for representing linear systems, geometric transformations, and many other applications in optimization and engineering.
Below is an example of a 2×2 matrix, with two rows and two columns.

In [24]:
matrix: np.ndarray = np.array([[1, 2], [3, 4]])
print('Matrix:\n', matrix)


Matrix:
 [[1 2]
 [3 4]]


NumPy provides simple functions to generate specific types of matrices that are frequently used in mathematics and optimization.
These include matrices filled with zeros or ones, and the identity matrix.
Such matrices are useful when initializing algorithms, setting up systems of equations, or testing matrix operations.
A matrix full of zeros.

In [25]:
all_zeros: np.ndarray = np.zeros([3, 2])
print('Zeros:\n', all_zeros)


Zeros:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


A matrix full of ones.

In [26]:
all_ones: np.ndarray = np.ones([2, 3])
print('Ones:\n', all_ones)


Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


The identity matrix is a square matrix with 1s on the diagonal and 0s elsewhere.
It acts like the number 1 in matrix multiplication: multiplying a matrix by the identity matrix leaves it unchanged.
The function is called `eye` because the identity matrix is often denoted by the letter "I" in mathematics.

In [27]:
identity: np.ndarray = np.eye(4)
print('Identity matrix:\n', identity)


Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


The transpose of a matrix is an operation that flips it over its diagonal,
turning its rows into columns and columns into rows.
For example, if a matrix has shape (2, 3), the transposed matrix will have shape (3, 2).
This is a common operation in linear algebra, especially when switching between row and column vectors.
In NumPy, you can get the transpose of a matrix using the `.T` attribute.

In [28]:
print('Transposed matrix:\n', matrix.T)


Transposed matrix:
 [[1 3]
 [2 4]]


You can access elements in a 2D NumPy array using the syntax [row_index, column_index].
Indexing starts at 0, so matrix[1, 0] refers to the element in the second row and first column.
This is different from traditional mathematical notation where indices often start at 1.

In [29]:
print('Element at row 2, column 1:', matrix[1, 0])


Element at row 2, column 1: 3


## Matrix Multiplication

Matrix multiplication is a fundamental operation in linear algebra, and NumPy makes it easy to perform.
You can multiply two 2D arrays (matrices) using either the `@` operator or the function `np.dot()`.
This operation follows the standard rules of linear algebra: the number of columns in the first matrix
must match the number of rows in the second matrix.

In the example below:
- Matrix A is a 2x2 matrix with elements [[1, 2], [3, 4]]
- Matrix B is another 2x2 matrix with elements [[5, 6], [7, 8]]
The product A @ B will result in a new 2x2 matrix where each element is computed as the dot product
of a row from A and a column from B.

In [30]:
A: np.ndarray = np.array([[1, 2], [3, 4]])
B: np.ndarray = np.array([[5, 6], [7, 8]])
product: np.ndarray = A @ B  # or np.dot(A, B)
print('Matrix Product A @ B:\n', product)

A: np.ndarray = np.array([[2, 1], [1, 3]])
b: np.ndarray = np.array([8, 13])
x: np.ndarray = np.linalg.solve(A, b)
print('Solution of the system Ax = b:', x)


Matrix Product A @ B:
 [[19 22]
 [43 50]]
Solution of the system Ax = b: [2.2 3.6]


## Solving linear systems

In many optimization and engineering problems, we encounter systems of linear equations of the form Ax = b,
where A is a matrix of coefficients, x is a vector of unknowns, and b is a vector of constants (right-hand side).
Solving such a system means finding the values of x that satisfy all the equations simultaneously.

NumPy provides a convenient function `np.linalg.solve(A, b)` that does exactly this:
it takes a square matrix A and a vector b, and returns the solution vector x.
Note: This method works only if A is square (same number of rows and columns) and non-singular (i.e., has an inverse).

In [31]:
A: np.ndarray = np.array([[2, 1], [1, 3]])
b: np.ndarray = np.array([8, 13])
x: np.ndarray = np.linalg.solve(A, b)
print('Solution of the system Ax = b:', x)


Solution of the system Ax = b: [2.2 3.6]


## Determinant Calculation

The determinant is a scalar value that can be computed from a square matrix.
It provides important information about the matrix, such as whether it is invertible.
In optimization and linear algebra, a non-zero determinant indicates that the matrix
has full rank and a unique solution exists for the system Ax = b.

NumPy provides the function np.linalg.det() to compute the determinant of a square matrix.
Below, we compute the determinant of matrix A and display the result.

In [32]:
det_A: float = np.linalg.det(A)
print('Determinant of matrix A:', det_A)

A: np.ndarray = np.array([[1, -1, 0, 1], [0, 0, 1, -1], [1, -1, 1, 0]])
rank = np.linalg.matrix_rank(A)
print('Rank of A: ', rank)


Determinant of matrix A: 5.000000000000001
Rank of A:  2


The rank of a matrix tells us how many linearly independent rows or columns it has.
In optimization, it is used to detect redundant constraints — constraints that do not affect the feasible region
because they are linear combinations of others.
NumPy provides the function `np.linalg.matrix_rank()` to compute this.

In [33]:
A: np.ndarray = np.array([[1, -1, 0, 1], [0, 0, 1, -1], [1, -1, 1, 0]])
print('Rank of A: ', rank)


Rank of A:  2


Consult the online NumPy documentation for additional features and examples:
https://numpy.org/doc/
This website provides detailed explanations and usage examples for NumPy functions,
which are very helpful if you want to explore more advanced operations or clarify how specific functions work.

# Importing modules and packages in Python

In Python, functionality is organized in *modules* (single `.py` files) and *packages* (folders
containing modules, usually with an `__init__.py`). You "bring" code into your script using
the `import` statement. Below are the most common patterns you'll use in this course.

## Import a whole module

You access names with the module prefix, which avoids name clashes and keeps code readable.

In [34]:
import math
print('cos(0) using math module:', math.cos(0))


cos(0) using math module: 1.0


## Import with an alias (a short nickname)

Common for widely used libraries (e.g., numpy as np, pandas as pd).

In [35]:
import math as m
print('cos(0) using alias m:', m.cos(0))


cos(0) using alias m: 1.0


## Import selected names from a module

This puts the names directly in your namespace (no prefix when calling them).

In [36]:
from math import sqrt, pi
print('sqrt(9) without prefix:', sqrt(9))
print('pi without prefix:', pi)


sqrt(9) without prefix: 3.0
pi without prefix: 3.141592653589793


## Import submodules or names from a *package*

You can import the whole submodule or only
certain names from it. The examples below are wrapped in try/except so this
notebook remains runnable even if the package is not installed yet.

In [50]:
try:
    # Import the submodule with an alias
    import teaching_optimization.linear_constraints as lc
    # Use a function via the alias (replace with real arguments when you have data)
    print('Submodule imported as lc. Available names example:', hasattr(lc, 'StandardForm'))
except ModuleNotFoundError:
    print('Package teaching_optimization not found. Install or ensure it is on PYTHONPATH.')

try:
    # Import specific names directly from the submodule
    from teaching_optimization.linear_constraints import (
        draw_polyhedron_standard_form,
        LabeledPoint,
        BoundingBox,
        StandardForm,
    )
    print('Specific names imported from teaching_optimization.linear_constraints.')
except ModuleNotFoundError:
    print('Cannot import names from teaching_optimization.linear_constraints (package not available).')


Package teaching_optimization not found. Install or ensure it is on PYTHONPATH.
Cannot import names from teaching_optimization.linear_constraints (package not available).


## Where does Python look for modules? (the import search path)

Python searches in: the current working directory, installed site-packages, and the
directories listed in sys.path. You can inspect or extend it at runtime.

In [51]:
import sys
print('Number of entries in sys.path:', len(sys.path))


Number of entries in sys.path: 5


## Installing third-party packages

Packages that do not come with Python must be installed (once) in your environment:
pip install teaching-optimization
or inside a notebook cell:  %pip install teaching-optimization
Make sure you are in the correct virtual environment so that the import will succeed.

## Summary:

- Use `import package.module as alias` for whole modules you call often.
- Use `from package.module import Name1, Name2` when you need only a few items [recommended].
- Keep imports at the top of your files, and use aliases consistently.
- If an import fails, check your virtual environment and installation (pip install ...).

# Getting documentation (help) for modules, packages, and functions

Python provides built‑in ways to access documentation and discover what a module contains.
This is very handy during the labs when you are unsure about a function's arguments
or want to know what is available inside a package like `teaching_optimization`.

## Built-in help for standard modules

You can use the `help`function to receive information about a module, a package or a function.

In [52]:
help(math)


Help on module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    cbrt(x, /)
        Return the cube root of x.

    ceil(x, /)
        Return the ceiling of x as an Integral.

        This is the sma

In [40]:
help(math.cos)


Help on built-in function cos in module math:

cos(x, /)
    Return the cosine of x (measured in radians).



## Inspect what a module exposes with `dir()`


In [41]:
list_of_functions = list(dir(math))


We print the first 10 functions

In [42]:
print(list_of_functions[:10])


['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh']


In general, names that begin with a single underscore (_) or double underscores (__)
are considered "internal" to the module. They are mainly used by Python itself
or by developers for special purposes, and are not intended for everyday use.
When exploring a module with help() or dir(), you can usually ignore these entries
and focus on the functions, classes, and variables without leading underscores.

In [43]:
print('Some names exported by math:', [name for name in list_of_functions if not name.startswith('_')][:10], '...')


Some names exported by math: ['acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb'] ...


## Tips

- In a notebook, you can type:  `help(object)`  or  `object?`  to open documentation.
- Use `dir(object)` to list attributes and functions.